# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SortIssueTemplate < Formula
  desc "Change the order of GitHub Issue Templates using a text editor
"
  homepage "https://github.com/suzuki-shunsuke/sort-issue-template"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.1/sort-issue-template_darwin_amd64.tar.gz"
      sha256 "ed07456faa31e927b069923678af3453d69b4c551dc84ce3c4e0bd0ac7b41e05"

      def install
        bin.install "sort-issue-template"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.1/sort-issue-template_darwin_arm64.tar.gz"
      sha256 "eb803987aede00dcbbba0b03fb469762578dc752d49c151f036492b76c2f90f1"

      def install
        bin.install "sort-issue-template"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.1/sort-issue-template_linux_amd64.tar.gz"
        sha256 "969dba676436620a6a7a8fa5d1d2e8c3e57bcdcfd04add2d583b3f7c414e2480"

        def install
          bin.install "sort-issue-template"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.1/sort-issue-template_linux_arm64.tar.gz"
        sha256 "be5a431ef5c3dce9c2898d9f3b1181ce038c93c89dfb335fd7a63718452a85e3"

        def install
          bin.install "sort-issue-template"
        end
      end
    end
  end

  test do
    system "#{bin}/sort-issue-template --version"
  end
end
