# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SortIssueTemplate < Formula
  desc "Change the order of GitHub Issue Templates using a text editor
"
  homepage "https://github.com/suzuki-shunsuke/sort-issue-template"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.2/sort-issue-template_darwin_amd64.tar.gz"
      sha256 "729454616f981ef504629d7ffc17be0c4a25dc365e0f992ba237f5793c8da4c9"

      def install
        bin.install "sort-issue-template"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.2/sort-issue-template_darwin_arm64.tar.gz"
      sha256 "32f9556903dd5819d7d1c232c87eac595cf6569e4ed55d219bc316aab531309f"

      def install
        bin.install "sort-issue-template"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.2/sort-issue-template_linux_amd64.tar.gz"
        sha256 "50efe40cade205afd60b18aa8c771b83fd5049c4b5600521aed2bf783aa9ffc0"

        def install
          bin.install "sort-issue-template"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.2/sort-issue-template_linux_arm64.tar.gz"
        sha256 "9b2fccf6d5ee6de8a517186b0a733487ac3f1562f9cda7ffbd058afe550ae52b"

        def install
          bin.install "sort-issue-template"
        end
      end
    end
  end

  test do
    system "#{bin}/sort-issue-template --version"
  end
end
