# This file was generated by GoReleaser. DO NOT EDIT.
cask "sort-issue-template" do
  desc "Change the order of GitHub Issue Templates using a text editor
"
  homepage "https://github.com/suzuki-shunsuke/sort-issue-template"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sort-issue-template"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.4/sort-issue-template_darwin_amd64.tar.gz"
      sha256 "83abe1233433276bae8703c9cf8612fe78d275e06b852ed088b40ad4490aa799"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.4/sort-issue-template_darwin_arm64.tar.gz"
      sha256 "190d6dfb7ef7e4f0f15baaf5c44457ad40e19ef56f3c60f85762401bc10d6e63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.4/sort-issue-template_linux_amd64.tar.gz"
      sha256 "cd23b40a28e1be9461cb78021329255dc106415a4c360800b67be6beeb4b268b"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.4/sort-issue-template_linux_arm64.tar.gz"
      sha256 "30b6589903b1ff9bad9866376530f817071f7c5fd705a679536a881f1a5ac386"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sort-issue-template"]
    end
  end

  # No zap stanza required
end
