# This file was generated by GoReleaser. DO NOT EDIT.
cask "sort-issue-template" do
  desc "Change the order of GitHub Issue Templates using a text editor
"
  homepage "https://github.com/suzuki-shunsuke/sort-issue-template"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sort-issue-template"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.3/sort-issue-template_darwin_amd64.tar.gz"
      sha256 "74e536e550fb87e5d4854b80f5b9a94448f60e4071adbb84b2e24de75a31e4e4"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.3/sort-issue-template_darwin_arm64.tar.gz"
      sha256 "cc4b5f827132115350e087e83e0d82862e9b1843d32cbbfb699644fd7d93d43d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.3/sort-issue-template_linux_amd64.tar.gz"
      sha256 "b01a7de2419dd3a195974d62908453b3b5b0e2300e7c99c1ff97232093644231"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/sort-issue-template/releases/download/v0.1.3/sort-issue-template_linux_arm64.tar.gz"
      sha256 "d5a9b41365afa8a3191a4549749040512c6abd7c9043b6decb0e1b6242fe56b7"
    end
  end

  # No zap stanza required
end
